export default [{
    path: '/welcome',
    exact: true,
    text: '欢迎',
    page: () => { return import('../app/Welcome'); },
},
{
    // 正式页面
    path: '/accountsmanage/class',
    exact: true,
    text: '科目管理',
    page: () => { return import('../app/AccountsManage/Class/List'); },
}, {
    path: '/accountsmanage/class/new',
    exact: true,
    text: '新增科目',
    page: () => { return import('../app/AccountsManage/Class/New'); },
}, {
    path: '/accountsmanage/class/new/:id',
    exact: true,
    text: '修改科目',
    page: () => { return import('../app/AccountsManage/Class/New'); },
}, {
    path: '/accountsmanage/class/detail/:id',
    exact: true,
    text: '查看科目',
    page: () => { return import('../app/AccountsManage/Class/Detail'); },
}, {
    path: '/accountsmanage/out',
    exact: true,
    text: '外部账户管理',
    page: () => { return import('../app/AccountsManage/Out/List'); },
}, {
    path: '/accountsmanage/out/detail/:id/:subjectNo',
    exact: true,
    text: '外部账户查看',
    page: () => { return import('../app/AccountsManage/Out/Detail'); },
}, {
    path: '/accountsmanage/inner',
    exact: true,
    text: '内部账户管理',
    page: () => { return import('../app/AccountsManage/Inner/List'); },
}, {
    path: '/accountsmanage/inner/new',
    exact: true,
    text: '内部账户开户',
    page: () => { return import('../app/AccountsManage/Inner/New'); },
}, {
    path: '/accountsmanage/inner/new/:id',
    exact: true,
    text: '内部账户修改',
    page: () => { return import('../app/AccountsManage/Inner/New'); },
}, {
    path: '/accountsmanage/inner/detail/:id',
    exact: true,
    text: '内部账户查看',
    page: () => { return import('../app/AccountsManage/Inner/Detail'); },
}, {
    path: '/accountsmanage/category',
    exact: true,
    text: '财务分类维护',
    page: () => { return import('../app/AccountsManage/Category/List'); },
}, {
    path: '/accountsmanage/category/new',
    exact: true,
    text: '新增财务分类',
    page: () => { return import('../app/AccountsManage/Category/New'); },
}, {
    path: '/accountsmanage/category/modify/:id/:level',
    exact: true,
    text: '财务分类修改',
    page: () => { return import('../app/AccountsManage/Category/Modify'); },
}, {
    path: '/accountsmanage/category/detail/:id/:level',
    exact: true,
    text: '财务分类查询',
    page: () => { return import('../app/AccountsManage/Category/Detail'); },
}, {
    path: '/accountsmanage/rule',
    text: '会计分录规则维护',
    exact: true,
    page: () => { return import('../app/AccountsManage/Rule/List'); },
}, {
    path: '/accountsmanage/rule/:type/:id',
    text: '会计分录规则管理',
    exact: true,
    page: () => { return import('../app/AccountsManage/Rule/New'); },
}, {
    path: '/accountquery/flow',
    exact: true,
    text: '记账流水查询',
    page: () => { return import('../app/AccountsQuery/Flow/List'); },
}, {
    path: '/accountquery/flow/detail/:id',
    exact: true,
    text: '记账流水详情',
    page: () => { return import('../app/AccountsQuery/Flow/Detail'); },
}, {
    path: '/accountquery/inout',
    exact: true,
    text: '账户收支明细',
    page: () => { return import('../app/AccountsQuery/Inout/List'); },
}, {
    path: '/accountquery/inout/detail/:id',
    exact: true,
    text: '账户收支详情',
    page: () => { return import('../app/AccountsQuery/Inout/Detail'); },
}, {
    path: '/accountquery/bussinesslist',
    exact: true,
    text: '业务流记账明细',
    page: () => { return import('../app/AccountsQuery/BussinessList'); },
}, {
    path: '/accountquery/innerbalance',
    exact: true,
    text: '内部账户余额查询',
    page: () => { return import('../app/AccountsQuery/InnerBalance/List'); },
}, {
    path: '/accountquery/innerhistorybalance',
    exact: true,
    text: '内部账户历史余额查询',
    page: () => { return import('../app/AccountsQuery/InnerHistoryBalance/List'); },
}, {
    path: '/verifymanage/process',
    exact: true,
    text: '对账进度管理',
    page: () => { return import('../app/VerifyManage/Process'); },
}, {
    path: '/verifymanage/errorhandle',
    exact: true,
    text: '对账差错处理',
    page: () => { return import('../app/VerifyManage/ErrorHandle/List'); },
}, {
    path: '/verifymanage/errorhandle/:type/:id',
    exact: true,
    text: '对账差错处理',
    page: () => { return import('../app/VerifyManage/ErrorHandle/Detail'); },
}, {
    path: '/verifymanage/handleverify',
    exact: true,
    text: '差错处理审核列表',
    page: () => { return import('../app/VerifyManage/ErrorHandleVerify/List'); },
}, {
    path: '/verifymanage/handleverify/:type/:id',
    exact: true,
    text: '差错处理审核',
    page: () => { return import('../app/VerifyManage/ErrorHandleVerify/Detail'); },
}, {
    path: '/verifymanage/gatherresult',
    exact: true,
    text: '对账汇总结果',
    page: () => { return import('../app/VerifyManage/GatherResult/List'); },
}, {
    path: '/verifymanage/gatherresult/detail/:id',
    exact: true,
    text: '对账汇总结果详情',
    page: () => { return import('../app/VerifyManage/GatherResult/Detail'); },
}, {
    path: '/verifymanage/bindincome',
    exact: true,
    text: '绑定进账单列表',
    page: () => { return import('../app/VerifyManage/BindIncome/List'); },
}, {
    path: '/verifymanage/bindincome/detail/:id',
    exact: true,
    text: '绑定进账单详情',
    page: () => { return import('../app/VerifyManage/BindIncome/Detail'); },
}, {
    path: '/verifymanage/bindincome/new/:id',
    exact: true,
    text: '绑定进账单新增',
    page: () => { return import('../app/VerifyManage/BindIncome/New'); },
}, {
    path: '/verifymanage/incomeverify',
    exact: true,
    text: '进账单审核列表',
    page: () => { return import('../app/VerifyManage/BindIncomeVerify/List'); },
}, {
    path: '/verifymanage/asset',
    exact: true,
    text: '资损管理列表',
    page: () => { return import('../app/VerifyManage/Asset/List'); },
}, {
    path: '/verifymanage/asset/:type/:id',
    exact: true,
    text: '资损管理详情',
    page: () => { return import('../app/VerifyManage/Asset/Detail'); },
}, {
    path: '/verifymanage/verifyasset',
    exact: true,
    text: '资损管理列表',
    page: () => { return import('../app/VerifyManage/AssetVerify/List'); },
}, {
    path: '/verifymanage/verifyasset/check/:id/:capitalLossOperateType',
    exact: true,
    text: '资损管理审核',
    page: () => { return import('../app/VerifyManage/AssetVerify/Detail'); },
}, {
    path: '/verifywarn/warnrule',
    exact: true,
    text: '告警维护规则列表',
    page: () => { return import('../app/VerifyWarn/WarnRule/List'); },
}, {
    path: '/verifywarn/warnrule/:type/:id',
    exact: true,
    text: '告警维护规则详情',
    page: () => { return import('../app/VerifyWarn/WarnRule/New'); },
}, {
    path: '/verifywarn/warncontact',
    exact: true,
    text: '告警通知联系人列表',
    page: () => { return import('../app/VerifyWarn/WarnContact/List'); },
}, {
    path: '/verifywarn/warncontact/:type',
    exact: true,
    text: '告警通知联系人列表',
    page: () => { return import('../app/VerifyWarn/WarnContact/New'); },
}, {
    path: '/verifywarn/warncontact/:type/',
    exact: true,
    text: '告警通知联系人列表',
    page: () => { return import('../app/VerifyWarn/WarnContact/New'); },
}, {
    path: '/verifywarn/warnrecord',
    exact: true,
    text: '告警通知联系人列表',
    page: () => { return import('../app/VerifyWarn/WarnRecord/List'); },
},
{
    path: '/clearmanage/outmoney',
    exact: true,
    text: '出金交易查询',
    page: () => { return import('../app/ClearManage/OutMoney/List'); },
}, {
    path: '/clearmanage/outmoney/detail/:id',
    exact: true,
    text: '出金交易详情',
    page: () => { return import('../app/ClearManage/OutMoney/Detail'); },
},
{
    path: '/clearmanage/statement',
    exact: true,
    text: '结算单列表',
    page: () => { return import('../app/ClearManage/Statement/List'); },
},
{
    path: '/clearmanage/statement/detail/:id',
    exact: true,
    text: '结算单详情',
    page: () => { return import('../app/ClearManage/Statement/Detail'); },
},
{
    path: '/clearmanage/paymanage/payoperate',
    exact: true,
    text: '付款操作',
    page: () => { return import('../app/ClearManage/PayManage/PayOperate/List'); },
},
{
    path: '/clearmanage/paymanage/payoperate/detail/:id',
    exact: true,
    text: '付款操作详情',
    page: () => { return import('../app/ClearManage/PayManage/PayOperate/Detail'); },
},
{
    path: '/clearmanage/paymanage/payverify',
    exact: true,
    text: '付款审核',
    page: () => { return import('../app/ClearManage/PayManage/PayVerify/List'); },
},
{
    path: '/clearmanage/paymanage/payverify/detail/:id',
    exact: true,
    text: '付款审核详情',
    page: () => { return import('../app/ClearManage/PayManage/PayVerify/Detail'); },
},
{
    path: '/clearmanage/paymanage/orgpay',
    exact: true,
    text: '合作机构备用金打款',
    page: () => { return import('../app/ClearManage/PayManage/OrgPay/List'); },
},
{
    path: '/clearmanage/paymanage/payprocess',
    exact: true,
    text: '付款进度查询',
    page: () => { return import('../app/ClearManage/PayManage/PayProcess/List'); },
},
{
    path: '/clearmanage/paymanage/payprocess/detail/:id',
    exact: true,
    text: '付款进度详情',
    page: () => { return import('../app/ClearManage/PayManage/PayProcess/Detail'); },
},
{
    path: '/clearmanage/paymanage/payfail',
    exact: true,
    text: '付款失败处理',
    page: () => { return import('../app/ClearManage/PayManage/PayFail/List'); },
},
{
    path: '/clearmanage/payebank',
    exact: true,
    text: '转网银付款管理',
    page: () => { return import('../app/ClearManage/PayEbankManage/List'); },
},
{
    path: '/clearmanage/acc/param',
    exact: true,
    text: '清分参数维护',
    page: () => { return import('../app/ClearManage/Acc/Param/List'); },
},
{
    path: '/clearmanage/acc/trade',
    exact: true,
    text: '交易清分查询',
    page: () => { return import('../app/ClearManage/Acc/Trade/List'); },
},
{
    path: '/clearinfomanage/orgbalance',
    exact: true,
    text: '',
    page: () => { return import('../app/ClearInfoManage/OrgBalance'); },
},
{
    path: '/clearinfomanage/merchant',
    exact: true,
    text: '商户账户收支明细列表',
    page: () => { return import('../app/ClearInfoManage/MerchantDetail/List'); },
},
{
    path: '/clearinfomanage/merchant/detail/:accountNo/:sequenceNum',
    exact: true,
    text: '商户账户收支明细详情',
    page: () => { return import('../app/ClearInfoManage/MerchantDetail/Detail'); },
},
{
    path: '/clearinfomanage/custom',
    exact: true,
    text: '客户账户收支明细列表',
    page: () => { return import('../app/ClearInfoManage/CustomDetail/List'); },
},
{
    path: '/clearinfomanage/custom/detail/:accountNo/:sequenceNum',
    exact: true,
    text: '客户账户收支明细详情',
    page: () => { return import('../app/ClearInfoManage/CustomDetail/Detail'); },
},
{
    path: '/tax/taxpush',
    exact: true,
    text: '纳税申报数据推送列表',
    page: () => { return import('../app/Tax/TaxPush/List'); },
},
{
    path: '/tax/taxpush/detail/:id',
    exact: true,
    text: '纳税申报数据推送详情',
    page: () => { return import('../app/Tax/TaxPush/Detail'); },
},
{
    path: '/payment/onbehalf',
    exact: true,
    text: '代付打款',
    page: () => { return import('../app/Payment/Onbehalf/List'); },
},
{
    path: '/payment/onbehalf/detail/:id',
    exact: true,
    text: '代付打款-详情',
    page: () => { return import('../app/Payment/Onbehalf/Detail'); },
},
{
    path: '/payment/onbehalf/reset/:id',
    exact: true,
    text: '代付打款-修改',
    page: () => { return import('../app/Payment/Onbehalf/Reset'); },
},
{
    path: '/payment/partner',
    exact: true,
    text: '合作机构打款',
    page: () => { return import('../app/Payment/Partner/List'); },
},
{
    path: '/settlementperido/merchant',
    exact: true,
    text: '结算周期-商户',
    page: () => { return import('../app/ClearManage/SettlementPeriod/MerchantLoan/List'); },
},
{
    path: '/settlementperido/supplier',
    exact: true,
    text: '结算周期-供应商',
    page: () => { return import('../app/ClearManage/SettlementPeriod/Supplier/List'); },
},
{
    path: '/settlementperido/bus',
    exact: true,
    text: '结算周期-业务',
    page: () => { return import('../app/ClearManage/SettlementPeriod/BusClear/List'); },
},
{
    path: '/settlementperido/merchant/:type/:id',
    exact: true,
    text: '结算周期-商户贷款-多功能页',
    page: () => { return import('../app/ClearManage/SettlementPeriod/MerchantLoan/Set'); },
},
{
    path: '/settlementperido/busclear/:type/:id',
    exact: true,
    text: '结算周期-业务-多功能页',
    page: () => { return import('../app/ClearManage/SettlementPeriod/BusClear/Set'); },
},
{
    path: '/spare/sparemanage',
    exact: true,
    text: '备用金-备用账户管理',
    page: () => { return import('../app/Spare/SpareManage/List'); },
},
{
    path: '/spare/riskrule',
    exact: true,
    text: '备用金-备用金账户风控规则',
    page: () => { return import('../app/Spare/Risk/RiskRule'); },
},
{
    path: '/spare/risktotal',
    exact: true,
    text: '备用金-风控累计',
    page: () => { return import('../app/Spare/Risk/RiskTotal'); },
},
{
    path: '/spare/accountdetail',
    exact: true,
    text: '备用金-备用金账户收支明细',
    page: () => { return import('../app/Spare/InoutDetail'); },
}, {
    path: '/settlementperido/supplier/:type/:id',
    exact: true,
    text: '结算周期-供应-多功能页',
    page: () => { return import('../app/ClearManage/SettlementPeriod/Supplier/Set'); },
},
{
    path: '/treasury/payment/staffmanage',
    exact: true,
    text: '金库日报-金库交款-门店金库人员管理-列表',
    page: () => { return import('../app/Treasury/TreasuryPayment/StaffManage/List'); },
},
{
    path: '/treasury/payment/receivespare',
    exact: true,
    text: '金库日报-金库交款-收银员领取备用金-列表',
    page: () => { return import('../app/Treasury/TreasuryPayment/ReveiveSpare/List'); },
},
{
    path: '/treasury/payment/receivenew',
    exact: true,
    text: '金库日报-金库交款-收银员领取备用金-新增领取',
    page: () => { return import('../app/Treasury/TreasuryPayment/ReveiveSpare/New'); },
},
{
    path: '/treasury/payment/receivenew/print',
    exact: true,
    text: '金库日报-金库交款-收银员领取备用金-打印',
    page: () => { return import('../app/Treasury/TreasuryPayment/ReveiveSpare/Print'); },
},
{
    path: '/treasury/payment/turnin',
    exact: true,
    text: '金库日报-金库交款-收银员交款-列表',
    page: () => { return import('../app/Treasury/TreasuryPayment/TurnInSpare/List'); },
},
{
    path: '/treasury/payment/turninnew',
    exact: true,
    text: '金库日报-金库交款-收银员交款-新增交款',
    page: () => { return import('../app/Treasury/TreasuryPayment/TurnInSpare/New'); },
},
{
    path: '/treasury/payment/staffdailytotal',
    exact: true,
    text: '金库日报-金库交款-收银员交款日汇总-列表',
    page: () => { return import('../app/Treasury/TreasuryPayment/TurnInDailyTotal/List'); },
},
{
    path: '/treasury/payment/staffdailytotal/detail/:saledate/:shopcode/:cashiercode',
    exact: true,
    text: '金库日报-金库交款-收银员交款日汇总-详情',
    page: () => { return import('../app/Treasury/TreasuryPayment/TurnInDailyTotal/Detail'); },
},
{
    path: '/treasury/payment/differencemanage',
    exact: true,
    text: '金库日报-金库交款-交款差额管理-列表',
    page: () => { return import('../app/Treasury/TreasuryPayment/DifferenceManage/List'); },
},
{
    path: '/treasury/payment/differencemanage/detail/:id',
    exact: true,
    text: '金库日报-金库交款-交款差额管理-详情',
    page: () => { return import('../app/Treasury/TreasuryPayment/DifferenceManage/Detail'); },
},
{
    path: '/treasury/payment/differencemanage/set/:id',
    exact: true,
    text: '金库日报-金库交款-交款差额管理-处理',
    page: () => { return import('../app/Treasury/TreasuryPayment/DifferenceManage/Set'); },
},
{
    path: '/treasury/payment/differenceverify',
    exact: true,
    text: '金库日报-金库交款-差额处理审核-列表',
    page: () => { return import('../app/Treasury/TreasuryPayment/DifferenceVerify/List'); },
},
{
    path: '/treasury/payment/differenceverify/detail/:id',
    exact: true,
    text: '金库日报-金库交款-差额处理审核-详情',
    page: () => { return import('../app/Treasury/TreasuryPayment/DifferenceVerify/Detail'); },
},
{
    path: '/treasury/payment/differenceverify/verify/:id',
    exact: true,
    text: '金库日报-金库交款-差额处理审核-审核',
    page: () => { return import('../app/Treasury/TreasuryPayment/DifferenceVerify/Verify'); },
},
{
    path: '/treasury/payment/tradeinout',
    exact: true,
    text: '金库日报-金库交款-交易流水查询-列表',
    page: () => { return import('../app/Treasury/TreasuryPayment/TradeInout/List'); },
},
{
    path: '/treasury/payment/bindmedia/cash',
    exact: true,
    text: '金库日报-金库交款-绑定进账影印件-现金存款影印件-列表',
    page: () => { return import('../app/Treasury/TreasuryPayment/BindMedia/Cash/List'); },
},
{
    path: '/treasury/payment/bindmedia/cash/new/:id/:shopCode/:createDate/:receivablesAmount',
    exact: true,
    text: '金库日报-金库交款-绑定进账影印件-现金存款影印件-上传',
    page: () => { return import('../app/Treasury/TreasuryPayment/BindMedia/Cash/New'); },
},
{
    path: '/treasury/storeDaily/list',
    exact: true,
    text: '金库日报-金库报表-门店日报-列表',
    page: () => { return import('../app/Treasury/StoreDaily/List'); },
},
{
    path: '/treasury/storeDaily/detail',
    exact: true,
    text: '金库日报-金库报表-门店日报-详情',
    page: () => {
        return import('../app/Treasury/StoreDaily/Detail');
    },
},
{
    path: '/treasury/thirdverify/process',
    exact: true,
    text: '金库日报-第三方对账管理-对账进度管理-列表',
    page: () => { return import('../app/Treasury/ThirdVerifyManage/Process'); },
},
{
    path: '/treasury/thirdverify/errorhandle',
    exact: true,
    text: '金库日报-第三方对账管理-对账差错处理-列表',
    page: () => { return import('../app/Treasury/ThirdVerifyManage/ErrorHandle/List'); },
},
{
    path: '/treasury/thirdverify/errorhandle/:type/:id',
    exact: true,
    text: '金库日报-第三方对账管理-对账差错处理-详情',
    page: () => { return import('../app/Treasury/ThirdVerifyManage/ErrorHandle/Detail'); },
},
{
    path: '/treasury/thirdverify/gatherresult',
    exact: true,
    text: '金库日报-第三方对账管理-对账汇总结果-列表',
    page: () => { return import('../app/Treasury/ThirdVerifyManage/GatherResult/List'); },
},
{
    path: '/treasury/thirdverify/gatherresult/detail/:id',
    exact: true,
    text: '金库日报-第三方对账管理-对账汇总结果-详情',
    page: () => { return import('../app/Treasury/ThirdVerifyManage/GatherResult/Detail'); },
},
{
    path: '/treasury/summaryPaymentDate',
    exact: true,
    text: '金库日报-金库交款-交款日汇总-列表',
    page: () => { return import('../app/Treasury/TreasuryPayment/SummaryPaymentDate/List'); },
},
{
    path: '/treasury/summaryPaymentDate/detail',
    exact: true,
    text: '金库日报-金库交款-交款日汇总-详情',
    page: () => { return import('../app/Treasury/TreasuryPayment/SummaryPaymentDate/Detail'); },
},
{
    path: '/treasury/complaintWithdrawal',
    exact: true,
    text: '金库日报-金库交款-投诉/提款-列表',
    page: () => { return import('../app/Treasury/TreasuryPayment/ComplaintWithdrawal/List'); },
},
];
