const config = {
    routeType: 'browser',
    menuPosition: 'left',
    openPaths: [
        '/',
        '/403',
        '/404',
        '/500',
        '/welcome',
        '/login',
        '/accountsmanage/class',
        '/accountsmanage/class/new',
        '/accountsmanage/class/new/:id',
        '/accountsmanage/class/detail/:id',
        '/accountsmanage/inner',
        '/accountsmanage/inner/new',
        '/accountsmanage/inner/new/:id',
        '/accountsmanage/inner/detail/:id',
        '/accountsmanage/category',
        '/accountsmanage/category/new',
        '/accountsmanage/category/modify/:id/:level',
        '/accountsmanage/category/detail/:id/:level',
        '/accountsmanage/rule',
        '/accountsmanage/rule/:type/:id',
        '/accountquery/flow',
        '/accountquery/flow/detail/:id',
        '/accountquery/inout',
        '/accountquery/inout/detail/:id',
        '/accountquery/bussinesslist',
        '/accountquery/innerbalance',
        '/accountquery/innerhistorybalance',
        '/verifymanage/errorhandle/:type/:id',
        '/verifymanage/gatherresult/:id',
        '/verifymanage/bindincome/detail/:id',
        '/verifymanage/bindincome/new/:id',
        '/verifywarn/warncontact/:type',
        '/clearmanage/outmoney/detail/:id',
        '/payment/onbehalf',
        '/payment/onbehalf/detail/:id',
        '/payment/partner',
        '/settlementperido/merchant',
        '/settlementperido/bus',
        '/treasury/storeDaily/detail',
        '/treasury/summaryPaymentDate/detail',
    ],
    hasPermission: false,
    hasBreadcrum: false,
    hasLogin: true,
    projectName: '结算中心',
    menus: [
        {
            name: '账务管理',
            key: '1280775837345320961',
            icon: 'appstore',
            children: [
                {
                    name: '科目管理',
                    key: '1281052538121912321',
                    icon: 'appstore',
                    path: '/accountsmanage/class',
                },
                {
                    name: '内部账户管理',
                    key: '1281052538121912321_1',
                    icon: 'appstore',
                    path: '/accountsmanage/inner',
                },
                {
                    name: '外部账户管理',
                    key: '1281053149181673474',
                    icon: 'appstore',
                    path: '/accountsmanage/out',
                },
                {
                    name: '账务分类维护',
                    key: '1281053337564643329',
                    icon: 'appstore',
                    path: '/accountsmanage/category',
                },
                {
                    name: '会计分录规则维护',
                    key: '1281053711818194946',
                    icon: 'appstore',
                    path: '/accountsmanage/rule',
                },
            ],
        },
        {
            name: '账务查询',
            key: '1281046953099952130',
            icon: 'appstore',
            children: [
                {
                    name: '记账流水查询',
                    key: '1281057621819686914',
                    icon: 'appstore',
                    path: '/accountquery/flow',
                },
                {
                    name: '账户收支明细',
                    key: '1281058139778482177',
                    icon: 'appstore',
                    path: '/accountquery/inout',
                },
                {
                    name: '业务流记账明细',
                    key: '2_3',
                    icon: 'appstore',
                    path: '/accountquery/bussinesslist',
                },
                {
                    name: '内部账户余额查询',
                    key: '2_4',
                    icon: 'appstore',
                    path: '/accountquery/innerbalance',
                },
                {
                    name: '内部账户历史余额查询',
                    key: '2_5',
                    icon: 'appstore',
                    path: '/accountquery/innerhistorybalance',
                },
            ],
        },
        {
            name: '对账管理',
            key: '3',
            icon: 'appstore',
            children: [
                {
                    name: '对账进度管理',
                    key: '3_1',
                    icon: 'appstore',
                    path: '/verifymanage/process',
                },
                {
                    name: '对账差错处理',
                    key: '3_2',
                    icon: 'appstore',
                    path: '/verifymanage/errorhandle',
                },
                {
                    name: '差错处理审核',
                    key: '3_3',
                    icon: 'appstore',
                    path: '/verifymanage/handleverify',
                },
                {
                    name: '对账汇总结果',
                    key: '3_4',
                    icon: 'appstore',
                    path: '/verifymanage/gatherresult',
                },
                {
                    name: '绑定进账单',
                    key: '3_5',
                    icon: 'appstore',
                    path: '/verifymanage/bindincome',
                },
                {
                    name: '进账单审核',
                    key: '3_6',
                    icon: 'appstore',
                    path: '/verifymanage/incomeverify',
                },
                {
                    name: '资损管理',
                    key: '3_7',
                    icon: 'appstore',
                    path: '/verifymanage/asset',
                },
                {
                    name: '资损处理审核',
                    key: '3_8',
                    icon: 'appstore',
                    path: '/verifymanage/verifyasset',
                },
            ],
        },
        {
            name: '对账告警',
            key: '4',
            icon: 'appstore',
            children: [
                {
                    name: '维护告警规则',
                    key: '4_1',
                    icon: 'appstore',
                    path: '/verifywarn/warnrule',
                },
                {
                    name: '告警通知联系人',
                    key: '4_2',
                    icon: 'appstore',
                    path: '/verifywarn/warncontact',
                },
                {
                    name: '告警通知记录',
                    key: '4_3',
                    icon: 'appstore',
                    path: '/verifywarn/warnrecord',
                },
            ],
        },
        {
            name: '清结算管理',
            key: '5',
            icon: 'appstore',
            children: [
                {
                    name: '出金交易查询',
                    key: '5_1',
                    icon: 'appstore',
                    path: '/clearmanage/outmoney',
                },
                {
                    name: '结算单查询',
                    key: '5_2',
                    icon: 'appstore',
                    path: '/clearmanage/statement',
                },
                {
                    name: '付款管理',
                    key: '5_3',
                    icon: 'appstore',
                    children: [
                        {
                            name: '付款操作',
                            key: '5_3_1',
                            icon: 'appstore',
                            path: '/clearmanage/paymanage/payoperate',
                        },
                        {
                            name: '付款审核',
                            key: '5_3_2',
                            icon: 'appstore',
                            path: '/clearmanage/paymanage/payverify',
                        },
                        {
                            name: '合作机构备付金打款',
                            key: '5_3_3',
                            icon: 'appstore',
                            path: '/clearmanage/paymanage/orgpay',
                        },
                        {
                            name: '付款进度查询',
                            key: '5_3_4',
                            icon: 'appstore',
                            path: '/clearmanage/paymanage/payprocess',
                        },
                        {
                            name: '付款失败处理',
                            key: '5_3_5',
                            icon: 'appstore',
                            path: '/clearmanage/paymanage/payfail',
                        },
                    ],
                },
                {
                    name: '转网银付款管理',
                    key: '5_5',
                    icon: 'appstore',
                    path: '/clearmanage/payebank',
                },
                {
                    name: '清分管理',
                    key: '5_6',
                    icon: 'appstore',
                    children: [
                        {
                            name: '清分参数维护',
                            key: '5_6_1',
                            icon: 'appstore',
                            path: '/clearmanage/acc/param',
                        },
                        {
                            name: '交易清分查询',
                            key: '5_6_2',
                            icon: 'appstore',
                            path: '/clearmanage/acc/trade',
                        },
                    ],
                },
                {
                    name: '结算信息管理',
                    key: '5_7',
                    icon: 'appstore',
                    children: [
                        {
                            name: '商户结算信息维护',
                            key: '5_7_1',
                            icon: 'appstore',
                            path: '/settlementperido/merchant',
                        },
                        {
                            name: '供应商结算信息维护',
                            key: '5_7_2',
                            icon: 'appstore',
                            path: '/settlementperido/supplier',
                        },
                        {
                            name: '业务结算信息维护',
                            key: '5_7_3',
                            icon: 'appstore',
                            path: '/settlementperido/bus',
                        },
                    ],
                },
            ],
        },
        {
            name: '结算信息管理',
            key: '6',
            icon: 'appstore',
            children: [
                {
                    name: '合作机构余额查询',
                    key: '6_1',
                    icon: 'appstore',
                    path: '/clearinfomanage/orgbalance',
                },
                // {
                //     name: '结算业务信息维护',
                //     key: '6_2',
                //     icon: 'appstore',
                //     path: '/clearinfomanage/clearbussiness/list',
                // },
                {
                    name: '商户账户收支明细',
                    key: '6_3',
                    icon: 'appstore',
                    path: '/clearinfomanage/merchant',
                },
                {
                    name: '客人账户收支明细',
                    key: '6_4',
                    icon: 'appstore',
                    path: '/clearinfomanage/custom',
                },
            ],
        },
        {
            name: '纳税申报',
            key: '7',
            icon: 'appstore',
            children: [
                {
                    name: '纳税申报数据推送',
                    key: '7_1',
                    icon: 'appstore',
                    path: '/tax/taxpush',
                },
            ],
        },
        {
            name: '批量代付打款',
            key: '8',
            icon: 'appstore',
            children: [{
                name: '代付打款',
                key: '8_1',
                icon: 'appstore',
                path: '/payment/onbehalf',
            }, {
                name: '合作机构打款',
                key: '8_2',
                icon: 'appstore',
                path: '/payment/partner',
            }],
        },
        {
            name: '备用账户管理',
            key: '9',
            icon: 'appstore',
            children: [
                {
                    name: '备用账户管理',
                    key: '9_1',
                    icon: 'appstore',
                    path: '/spare/sparemanage',
                },
                {
                    name: '备用金风控',
                    key: '9_2',
                    icon: 'appstore',
                    children: [
                        {
                            name: '备用金账户风控规则',
                            key: '9_2_1',
                            icon: 'appstore',
                            path: '/spare/riskrule',
                        },
                        {
                            name: '风控累计',
                            key: '9_2_2',
                            icon: 'appstore',
                            path: '/spare/risktotal',
                        },
                    ],
                },
                {
                    name: '备用金账户收支明细',
                    key: '9_3',
                    icon: 'appstore',
                    path: '/spare/accountdetail',
                },
            ],
        },
        {
            name: '金库日报',
            key: '10',
            icon: 'appstore',
            children: [
                {
                    name: '金库交款',
                    key: '10_1',
                    icon: 'appstore',
                    children: [
                        {
                            name: '门店金库人员管理',
                            key: '10_1_1',
                            icon: 'appstore',
                            path: '/treasury/payment/staffmanage',
                        },
                        {
                            name: '收银员领取备用金',
                            key: '10_1_2',
                            icon: 'appstore',
                            path: '/treasury/payment/receivespare',
                        },
                        {
                            name: '收银员交款',
                            key: '10_1_3',
                            icon: 'appstore',
                            path: '/treasury/payment/turnin',
                        },
                        {
                            name: '收银员交款日汇总',
                            key: '10_1_4',
                            icon: 'appstore',
                            path: '/treasury/payment/staffdailytotal',
                        },
                        {
                            name: '交款差额管理',
                            key: '10_1_5',
                            icon: 'appstore',
                            path: '/treasury/payment/differencemanage',
                        },
                        {
                            name: '差额处理审核',
                            key: '10_1_6',
                            icon: 'appstore',
                            path: '/treasury/payment/differenceverify',
                        },
                        {
                            name: '交易流水查询',
                            key: '10_1_7',
                            icon: 'appstore',
                            path: '/treasury/payment/tradeinout',
                        },
                        {
                            name: '绑定进账影印件',
                            key: '10_1_8',
                            icon: 'appstore',
                            children: [
                                {
                                    name: '现金存款影印件',
                                    key: '10_1_8_1',
                                    icon: 'appstore',
                                    path: '/treasury/payment/bindmedia/cash',
                                },
                            ],
                        },
                        {
                            name: '投诉/提款',
                            key: '10_1_9',
                            icon: 'appstore',
                            path: '/treasury/ComplaintWithdrawal',
                        },
                        {
                            name: '门店交款日汇总',
                            key: '10_1_10',
                            icon: 'appstore',
                            path: '/treasury/SummaryPaymentDate',
                        },
                    ],
                },
                {
                    name: '金库报表',
                    key: '10_2',
                    icon: 'appstore',
                    children: [
                        {
                            name: '门店日报',
                            key: '10_2_1',
                            icon: 'appstore',
                            path: '/treasury/storeDaily/list',
                        },
                    ],
                },
                {
                    name: '第三方对账管理',
                    key: '10_3',
                    icon: 'appstore',
                    children: [
                        {
                            name: '对账进度管理',
                            key: '10_3_1',
                            icon: 'appstore',
                            path: '/treasury/thirdverify/process',
                        },
                        {
                            name: '对账差错处理',
                            key: '10_3_2',
                            icon: 'appstore',
                            path: '/treasury/thirdverify/errorhandle',
                        },
                        {
                            name: '对账汇总结果',
                            key: '10_3_4',
                            icon: 'appstore',
                            path: '/treasury/thirdverify/gatherresult',
                        },
                    ],
                },
            ],
        },
    ],
};

module.exports = config;
